version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  api_proxy:
    build: ./api_proxy
    ports:
      - "5000:5000"
    depends_on:
      - redis

  heartbeat:
    build: ./heartbeat
    depends_on:
      - api_proxy
      - redis

  logger:
    build: ./log
    depends_on:
      - redis
